### ISSUE TITLE
Link Underline

### ISSUE THREAD

**Issue by mikesoltis** [backdrop-contrib/quicktabs#1]
Issue: 
Underline should not be shown.

Setup:
I set up 2 tabs using Quicktabs and displayed the block on a basic page. 

When the option "Default Tab" in the Quicktabs setup is used to display a particular tab when the page is loaded, the page correctly displays the default tab.  However, the default tab title is underlined.  It should not be underlined since it is being displayed.

Additional info:
When either tab is subsequently clicked on, the title for the tab that is displayed is not underlined.

**Comment by herbdool** [comment]
This works as expected. It is expected that someone will either enable the Quicktabs Styles submodule, or they will style it themselves. Otherwise, you're getting a completely unstyled set of tabs.
